import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, FileText, Tag, UserRound } from 'lucide-react';
import { sanitizeArticleHtml } from './ArticlePage';
import type { ArticleItem } from './ArticlePage';

function getArticleIdFromHash() { return window.location.hash.startsWith('#/artikel/') ? decodeURIComponent(window.location.hash.slice('#/artikel/'.length)) : null; }

function formatDate(value: string | null) {
  return value ? new Date(`${value}T12:00:00`).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Tanggal belum diisi';
}

export default function PublicArticlePage({ articles, limitToTwo = false, onOpenAll, onBack }: { articles: ArticleItem[]; limitToTwo?: boolean; onOpenAll?: () => void; onBack?: () => void }) {
  const [selected, setSelected] = useState<ArticleItem | null>(null);
  const [category, setCategory] = useState('all');
  const [tag, setTag] = useState('all');
  const tags = useMemo(() => Array.from(new Set(articles.flatMap(article => article.tags ?? []))).sort((a, b) => a.localeCompare(b, 'id')), [articles]);
  const categories = useMemo(() => Array.from(new Set(articles.map(article => article.category).filter(Boolean))) as string[], [articles]);
  const visible = useMemo(() => articles.filter(article => (category === 'all' || article.category === category) && (tag === 'all' || (article.tags ?? []).includes(tag))), [articles, category, tag]); useEffect(() => { const syncSelected = () => { const articleId = getArticleIdFromHash(); setSelected(articleId ? articles.find(article => article.id === articleId) ?? null : null); }; syncSelected(); window.addEventListener('hashchange', syncSelected); return () => window.removeEventListener('hashchange', syncSelected); }, [articles]); const openArticle = (article: ArticleItem) => { window.location.hash = `#/artikel/${encodeURIComponent(article.id)}`; }; const clearArticleRoute = () => { window.location.hash = '#artikel-ranting'; };

  if (selected) return <section className="publicArticleDetailSection"><button className="publicBackButton" onClick={clearArticleRoute}><ChevronLeft size={17} /> Kembali ke Artikel</button><article className="publicArticleDetail"><div className="publicArticleCategory">{selected.category || 'Berita'}</div>{selected.cover_url && <img className="publicArticleHeroImage" src={selected.cover_url} alt={`Cover ${selected.title}`} />}<h1>{selected.title}</h1>{selected.subtitle && <p className="publicArticleDeck">{selected.subtitle}</p>}<div className="publicArticleMeta"><span><CalendarDays size={15} /> {formatDate(selected.publish_date)}</span><span><UserRound size={15} /> {selected.author || 'Tim Redaksi'}</span></div>{(selected.tags ?? []).length > 0 && <div className="publicArticleTags">{selected.tags!.map(item => <button key={item} onClick={() => { setTag(item); clearArticleRoute(); }}><Tag size={12} /> {item}</button>)}</div>}<div className="publicArticleAuthor"><div className="publicAuthorAvatar">{selected.author_photo_url ? <img src={selected.author_photo_url} alt={selected.author || 'Penulis'} /> : <UserRound size={24} />}</div><div><strong>Ditulis oleh {selected.author || 'Tim Redaksi'}</strong><span>{selected.author_role || 'Kontributor IPNU-IPPNU Tembok Kidul'}</span>{selected.author_bio && <p>{selected.author_bio}</p>}</div></div>{selected.excerpt && <p className="publicArticleExcerpt">{selected.excerpt}</p>}<div className="publicArticleBody" dangerouslySetInnerHTML={{ __html: sanitizeArticleHtml(selected.content) }} /></article></section>;

  const displayed = limitToTwo ? visible.slice(0, 2) : visible;
  return <section className={limitToTwo ? 'publicArticlesSection' : 'publicArticlesSection publicArticlesFullPage'} id="artikel">{onBack && <button className="publicBackButton" onClick={onBack}><ChevronLeft size={17} /> Kembali ke Beranda</button>}<div className="publicArticlesIntro"><div><span className="sectionLabel">BERITA & INFORMASI</span><h2>{limitToTwo ? <>Artikel <em>Terbaru.</em></> : <>Semua <em>Artikel.</em></>}</h2><p>{limitToTwo ? 'Berita, kegiatan, gagasan, dan informasi terbaru dari IPNU-IPPNU Tembok Kidul.' : 'Seluruh berita, kegiatan, gagasan, dan informasi yang telah diterbitkan oleh IPNU-IPPNU Tembok Kidul.'}</p></div><FileText size={32} /></div><div className="publicArticleFilters"><button className={category === 'all' ? 'publicTopic active' : 'publicTopic'} onClick={() => setCategory('all')}>Semua</button>{categories.map(item => <button className={category === item ? 'publicTopic active' : 'publicTopic'} key={item} onClick={() => setCategory(item)}>{item}</button>)}<select value={tag} onChange={event => setTag(event.target.value)} aria-label="Pilih tag artikel"><option value="all">Semua tag</option>{tags.map(item => <option key={item} value={item}>#{item}</option>)}</select></div>{displayed.length ? <div className="publicArticleGrid">{displayed.map(article => <button className="publicArticleCard" key={article.id} onClick={() => openArticle(article)}>{article.cover_url ? <img src={article.cover_url} alt={`Cover ${article.title}`} /> : <div className="publicArticleNoCover"><FileText size={26} /></div>}<div className="publicArticleCardBody"><span>{article.category || 'Berita'}</span><h3>{article.title}</h3>{article.subtitle && <p>{article.subtitle}</p>}<small><UserRound size={13} /> {article.author || 'Tim Redaksi'} <i>•</i> {formatDate(article.publish_date)}</small>{(article.tags ?? []).length > 0 && <div className="publicCardTags">{article.tags!.slice(0, 4).map(item => <em key={item}>#{item}</em>)}</div>}</div><ChevronRight className="publicArticleArrow" size={18} /></button>)}</div> : <div className="publicArticleEmpty"><FileText size={30} /><strong>Belum ada artikel terbit</strong><p>Artikel yang sudah berstatus Terbit akan tampil di sini.</p></div>}{limitToTwo && articles.length > 2 && <button className="publicMoreButton" onClick={onOpenAll}>Lihat selengkapnya <ChevronRight size={17} /></button>}</section>;
}
